import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"],
  weight: [ "200" , "300", "400", "500","600" , "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jakarta.className}`}>{children}</body>
    </html>
  );
}
