# This is a basic workflow to help you get started with Actions

name: markdown

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run parse-readme.js
        run: node docs/parse-readme.js

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v4
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'Update data.js'
    
